<?php
  require('inc/reg_post_types.php');
  require('inc/reg_taxonomies.php');
  require('inc/reg_media.php');
  require('inc/reg_hooks.php');
  require('inc/shortcodes.php');
  require('inc/reg_page_menu.php');
  require('inc/reg_widgets.php');
 ?>
